### ISSUE TITLE
Problem in Redmine 1.4.0

### ISSUE THREAD

**Issue by jwalkerbg** [commandprompt/redmine_pastebin#12]
Hi,

Following error arises in Redmine 1.4.0:

=================start log=====================
Processing ApplicationController#index (for 192.168.1.5 at 2012-04-14 22:58:02) [GET]
  Parameters: {"project_id"=>"first", "action"=>"index", "controller"=>"pastes"}

NoMethodError (undefined method `accept_key_auth' for PastesController:Class):
  vendor/plugins/redmine_pastebin/app/controllers/pastes_controller.rb:26
  d:/Ruby187/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
  d:/Ruby187/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  d:/Ruby187/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
  d:/Ruby187/lib/ruby/1.8/webrick/server.rb:162:in `start'
  d:/Ruby187/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
  d:/Ruby187/lib/ruby/1.8/webrick/server.rb:95:in `start'
  d:/Ruby187/lib/ruby/1.8/webrick/server.rb:92:in`each'
  d:/Ruby187/lib/ruby/1.8/webrick/server.rb:92:in `start'
  d:/Ruby187/lib/ruby/1.8/webrick/server.rb:23:in`start'
  d:/Ruby187/lib/ruby/1.8/webrick/server.rb:82:in `start'

Rendering D:/biz/apps/redmine_trunk/public/500.html (500 Internal Server Error)
rnal Server Error)
=================end log======================

**Comment by a1exsh** [comment]
Fixed in f7760138efb65bc727fbad2a3b87b5694cdc7557, thanks for heads up!
