### ISSUE TITLE
Non-viewable secure pastes show up in the activity feed

### ISSUE THREAD

**Issue by jawilson** [commandprompt/redmine_pastebin#19]
Secure pastes by other users show up in the activity list for all users with paste view permissions. This means they can see a preview of the paste, even though the link returns a 404.

**Comment by a1exsh** [comment]
This is now fixed in 00764fb.  Thank you for the report!

**Comment by jawilson** [comment]
Wow, thanks for the quick turn around! Your commit fixed the the issue, but now I can see pastes from all projects in the project activity feeds. Also, it's worth noting that fix requires ruby >=1.9 because of the default lambda value, which I had to upgrade on my setup.

**Comment by a1exsh** [comment]
Heh, fixed now in 31959ec...  what a mess! Thank you again for reporting this.

**Comment by jawilson** [comment]
Works great! Thanks for the helpful plugin and the support.
