### ISSUE TITLE
How to refer pastes in Wiki and issues?

### ISSUE THREAD

**Issue by jwalkerbg** [commandprompt/redmine_pastebin#20]
How to refer pastes in Wiki and issues? Is there some macro defined?

**Comment by a1exsh** [comment]
Well, this feature was on my list, but I never actually get to implement it.  I think something like {paste:###} wiki-macro should work.

**Comment by a1exsh** [comment]
Actually, it was easier than I thought.  Please see: e6d46c8

**Comment by jwalkerbg** [comment]
Is it easy to add paste's title (if any available) as title of the link?

**Comment by jwalkerbg** [comment]
Yes, I mean this:

<!a href="http://redmine.ourcompany.com/pastes/10">I mean this<!/a>

"I mean this" is content of :paste_title. (I put '!' so as to github  not render http link.)

**Comment by a1exsh** [comment]
OK, that makes sense.  Please see this commit: 9eebf3b
