### ISSUE TITLE
errors when running plugin in redmine 2.3..

### ISSUE THREAD

**Issue by stepps** [commandprompt/redmine_pastebin#22]
I get the following errors when running this plugin in redmine 2.3.2, ruby 1.8.7 (2011-06-30 patchlevel 352) [i386-linux]

Started GET "/projects/imsa/pastes" for 10.111.1.3 at Thu Nov 07 16:14:31 -0500 2013
Processing by PastesController#index as HTML
  Parameters: {"project_id"=>"imsa"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 7ms

SyntaxError (/var/www/redmine/plugins/redmine_pastebin/app/models/paste.rb:50: syntax error, unexpected '=', expecting '|'
  scope :visible, lambda{ |user=User.current, *args|
                                ^
/var/www/redmine/plugins/redmine_pastebin/app/models/paste.rb:50: syntax error, unexpected '|', expecting '='
/var/www/redmine/plugins/redmine_pastebin/app/models/paste.rb:60: syntax error, unexpected '}', expecting kEND):
  activesupport (3.2.13) lib/active_support/dependencies.rb:251:in `require'
  activesupport (3.2.13) lib/active_support/dependencies.rb:251:in`require'
  activesupport (3.2.13) lib/active_support/dependencies.rb:236:in `load_dependency'
  activesupport (3.2.13) lib/active_support/dependencies.rb:251:in`require'
  activesupport (3.2.13) lib/active_support/dependencies.rb:359:in `require_or_load'
  activesupport (3.2.13) lib/active_support/dependencies.rb:502:in`load_missing_constant'
  activesupport (3.2.13) lib/active_support/dependencies.rb:192:in `const_missing'
  activesupport (3.2.13) lib/active_support/dependencies.rb:190:in`each'
  activesupport (3.2.13) lib/active_support/dependencies.rb:190:in `const_missing'
  activesupport (3.2.13) lib/active_support/dependencies.rb:514:in`load_missing_constant'
  activesupport (3.2.13) lib/active_support/dependencies.rb:192:in `const_missing'
  activesupport (3.2.13) lib/active_support/dependencies.rb:190:in`each'
  activesupport (3.2.13) lib/active_support/dependencies.rb:190:in `const_missing'
  plugins/redmine_pastebin/app/controllers/pastes_controller.rb:98:in`find_paste_and_project'

**Comment by a1exsh** [comment]
Sorry, that's Ruby-1.9.x syntax being used in that line.

**Comment by stepps** [comment]
Ugh.
Well, thanks for your swift reply. Please add a comment on the main page so people knows.

**Comment by a1exsh** [comment]
Well, 1.8.7 is EOL.  Everyone _should_ be using 1.9.3 or newer anyway.
