### ISSUE TITLE
admin-only?

### ISSUE THREAD

**Issue by posativ** [commandprompt/redmine_pastebin#8]
Hey,

I've installed redmine_pastebin but it is only accessible when logged in as admin. I hope, that's not the intention? As registered user (manager, reporter) I am unable to add snippets because I get 403.

**Comment by a1exsh** [comment]
Maybe you need to set permissions appropriately?  By default no role has any permission to view/edit pastes...

**Comment by posativ** [comment]
Ah, yes I see. Would be worth, to add it to a readme, imho.

**Comment by a1exsh** [comment]
Well, yes.  At least it's mentioned here: http://www.redmine.org/plugins/pastebin under Installation notes :-p

**Comment by posativ** [comment]
Ooops, didn't read the last line. Thanks for the quick reply btw.
